server:
  port: 8072
eureka:
  instance:
   preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka


spring:
  cloud:
    loadbalancer.ribbon.enabled: false

    gateway:
        actuator:
          enabled: true
        discovery.locator:
          enabled: true
        lowerCaseServiceId: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  security:
    enabled: false
    management:
      security:
        enabled: false